# Generated by Django 4.2.19 on 2025-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='full_text',
            field=models.TextField(default=''),
        ),
    ]
