# Generated by Django 4.2.20 on 2025-05-22 08:04

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0005_alter_newsarticle_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
